/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Edgar Ruben B
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazH1
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAtras = new javax.swing.JButton();
        jLabelImagen1 = new javax.swing.JLabel();
        jLabelImagen2 = new javax.swing.JLabel();
        jLabelTexto1 = new javax.swing.JLabel();
        jLabelTexto2 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAtras.setBackground(new java.awt.Color(102, 102, 255));
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setText("Salir");
        jButtonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jLabelImagen1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaces/Inscripcion2.png"))); // NOI18N
        getContentPane().add(jLabelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 210, 210));

        jLabelImagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaces/INF.png"))); // NOI18N
        getContentPane().add(jLabelImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 240, 240));

        jLabelTexto1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTexto1.setForeground(new java.awt.Color(102, 153, 255));
        jLabelTexto1.setText("INSCRIPCION");
        jLabelTexto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jLabelTexto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTexto1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelTexto1MouseMoved(evt);
            }
        });
        jLabelTexto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTexto1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTexto1MouseExited(evt);
            }
        });
        getContentPane().add(jLabelTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        jLabelTexto2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTexto2.setForeground(new java.awt.Color(102, 153, 255));
        jLabelTexto2.setText("INFORMACION");
        jLabelTexto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        jLabelTexto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTexto2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabelTexto2MouseMoved(evt);
            }
        });
        jLabelTexto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTexto2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTexto2MouseExited(evt);
            }
        });
        getContentPane().add(jLabelTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesInterfaces/FondoAzul2.jpg"))); // NOI18N
        jLabelFondo.setPreferredSize(new java.awt.Dimension(15, 80));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton para salir del programa
    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    //Coloca un borde blanco rodeando al JLabel cuando detecta movimiento del mouse por encima de el
    private void jLabelTexto1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTexto1MouseMoved
        jLabelTexto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabelTexto1MouseMoved
    
    //Coloca un borde azul rodeando al JLabel cuando el mouse deja de estar encima de el
    private void jLabelTexto1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTexto1MouseExited
        jLabelTexto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,51,102)));
    }//GEN-LAST:event_jLabelTexto1MouseExited

    //Coloca un borde blanco rodeando al JLabel cuando detecta movimiento del mouse por encima de el
    private void jLabelTexto2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTexto2MouseMoved
        jLabelTexto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jLabelTexto2MouseMoved

    //Coloca un borde azul rodeando al JLabel cuando el mouse deja de estar encima de el
    private void jLabelTexto2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTexto2MouseExited
        jLabelTexto2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,51,102)));
    }//GEN-LAST:event_jLabelTexto2MouseExited

    //Cierra esta ventana para ir a la ventana de inscripcion
    private void jLabelTexto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTexto1MouseClicked
        Inscripcion interfaz= new Inscripcion();
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelTexto1MouseClicked

    //Cierra esta ventana para ir a la ventana de informacion
    private void jLabelTexto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTexto2MouseClicked
        Informacion interfaz= new Informacion();
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelTexto2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagen1;
    private javax.swing.JLabel jLabelImagen2;
    private javax.swing.JLabel jLabelTexto1;
    private javax.swing.JLabel jLabelTexto2;
    // End of variables declaration//GEN-END:variables
}
